version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: itcatcetc
      MYSQL_DATABASE: smarthome
      MYSQL_USER: itcatcetc
      MYSQL_PASSWORD: itcatcetc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: db
      DATABASE_PORT: 3306
      DATABASE_NAME: smarthome
      DATABASE_USER: itcatcetc
      DATABASE_PASSWORD: itcatcetc
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
networks:
  default:

volumes:
  mysql_data:
