version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: itcatcetc
      MYSQL_DATABASE: smarthome
      MYSQL_USER: itcatcetc
      MYSQL_PASSWORD: itcatcetc
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      PORT: 80
      DATABASE_URL: db
      DATABASE_PORT: 3306
      DATABASE_NAME: smarthome
      DATABASE_USER: itcatcetc
      DATABASE_PASSWORD: itcatcetc
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
